[package]
name = "filesystem-service"
version = "0.1.0"
edition = "2024"

[dependencies]
ext4plus = { git = "https://github.com/arihant2math/ext4plus", rev = "382b9e0a65a4b5155015992aee74ff2a798764f8", default-features = false, features = ["multi-threaded", "sync"] }

[target.'cfg(target_os = "mochios")'.dependencies]
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform", default-features = false, features = ["std"] }

[lib]
path = "src/lib.rs"
