[workspace]
resolver = "2"
members = [
    "capability",
    "compositor",
    "core",
    "display",
    "drivers",
    "input",
    "logger",
    "network",
    "package",
    "service-manager",
    "secure-ui",
    "signature",
    "tty",
    "update",
    "user",
]

[patch.crates-io]
mnu-abi = { git = "https://github.com/mochiOS/mnu", package = "mnu-abi" }
