[workspace]
resolver = "2"
members = [
    "capability",
    "compositor",
    "core",
    "display",
    "drivers",
    "input",
    "logger",
    "network",
    "package",
    "service-manager",
    "signature",
    "tty",
]

[patch."https://github.com/mochiOS/mnu"]
plugkit = { path = "../core/crates/PlugKit/plugkit" }
