[core.service]
dir = "core"
fs = "initfs"
description = "mochiOS core service"
autostart = true
order = 0

[capability.service]
dir = "capability"
fs = "rootfs"
description = "mochiOS capability and delegation service"
autostart = false
order = 1

[drivers.service]
dir = "drivers"
fs = "rootfs"
description = "mochiOS driver manager service"
autostart = false
order = 2

[input.service]
dir = "input"
fs = "rootfs"
description = "mochiOS input event service"
autostart = false
order = 3

[package.service]
dir = "package"
fs = "rootfs"
description = "mochiOS package installation service"
autostart = false
order = 4

[signature.service]
dir = "signature"
fs = "rootfs"
description = "mochiOS package signature verification service"
autostart = false
order = 5

[tty.service]
dir = "tty"
fs = "rootfs"
description = "mochiOS tty service"
autostart = false
order = 6
