//! システムコール ABI の共通定義

pub use mnu_abi::{
    SyscallNumber, EACCES, EAGAIN, EBADF, EFAULT, EEXIST, EINVAL, EIO, EMFILE, ENOENT, ENODATA,
    ENOMEM, ENOSYS, ENOTDIR, ENOTSUP, ENOTTY, ENXIO, EPERM, EPIPE, ERANGE, ESRCH, SUCCESS,
};
