[package]
id = "org.mochios.mboot-agent"
name = "mBoot Agent"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/mboot-agent.service"
kind = "service"
requires = [
    "dma.allocate",
    "ipc.server",
    "process.inspect",
    "serial.access",
    "system.random.read",
    "system.time.read",
]
