[package]
id = "org.mochios.secure-ui"
name = "Secure UI Service"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/secure-ui.service"
kind = "service"
requires = [
    "account.authenticate",
    "account.other.modify",
    "account.other.read",
    "fs.read.all",
    "fs.write.all",
    "ipc.client",
    "ipc.server",
    "system.time.read",
    "window.secure-overlay",
]
