[package]
name = "network"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
test-web-pki = ["mochios-tls-client/test-web-pki"]

[dependencies]
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform" }
mochi-user-runtime = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-runtime" }
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
mochios-net-device-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-net-device-protocol" }
mochios-network-stack = { git = "https://github.com/mochiOS/syscalls", package = "mochios-network-stack" }
mochios-tls-client = { git = "https://github.com/mochiOS/syscalls", package = "mochios-tls-client" }
mochios-http-client = { git = "https://github.com/mochiOS/syscalls", package = "mochios-http-client" }
getrandom = { version = "0.2.17", features = ["custom"] }

[[bin]]
name = "network"
path = "src/main.rs"
test = false
bench = false
harness = false
