[service]
id = "org.mochios.compositor"
name = "Compositor Service"
version = "1"
entry = "compositor.service"

[capabilities]
requires = [
    "display.read",
    "fs.read.all",
    "input.keyboard",
    "input.pointer",
    "ipc.client",
    "ipc.server",
]
