[service]
id = "com.mochios.drivers"
name = "Drivers Service"
version = "1"
entry = "drivers.service"

[capabilities]
requires = [
    "fs.read.all",
    "process.spawn",
    "device.input",
    "usb.access",
]
