[service]
id = "org.mochios.drivers"
name = "Drivers Service"
version = "1"
entry = "drivers.service"

[capabilities]
requires = [
    "fs.read.all",
    "process.spawn",
    "device.input",
    "display.read",
    "input.keyboard",
    "input.pointer",
    "ipc.client",
    "ipc.server",
    "usb.access",
]
