[package]
id = "org.mochios.drivers"
name = "Drivers Service"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/drivers.service"
kind = "service"
requires = [
    "fs.read.all",
    "process.spawn",
    "device.input",
    "display.read",
    "input.keyboard",
    "input.pointer",
    "ipc.client",
    "ipc.server",
    "usb.access",
    "window.create",
    "window.overlay",
]
