[package]
name = "display"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
mochios-virtio-gpu-protocol = { path = "../../user/crates/virtio-gpu-protocol" }
mochi-user-platform = { path = "../../user/crates/platform" }
mochi-user-runtime = { path = "../../user/crates/runtime" }
mochi-user-syscall = { path = "../../user/crates/syscall" }
plugkit = { path = "../../core/crates/PlugKit/plugkit" }

[[bin]]
name = "display"
path = "src/main.rs"
test = false
bench = false
harness = false
