[package]
name = "display"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
mochios-virtio-gpu-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-virtio-gpu-protocol" }
mochios-viewkit-gpu-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-viewkit-gpu-protocol" }
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform" }
mochi-user-runtime = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-runtime" }
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
plugkit = { git = "https://github.com/mochiOS/mnu", package = "plugkit" }

[[bin]]
name = "display"
path = "src/main.rs"
test = false
bench = false
harness = false
