[package]
id = "org.mochios.tty"
name = "TTY Service"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/tty.service"
kind = "service"
requires = [
    "fs.read.all",
    "process.spawn",
    "ipc.client",
    "ipc.server",
]
