[service]
id = "com.mochios.capability"
name = "Capability Service"
version = "1"
entry = "capability.service"

[capabilities]
requires = [
    "fs.read.all",
    "process.spawn",
    "service.register",
    "device.input",
    "ipc.server",
    "usb.access",
]
