[package]
id = "org.mochios.capability"
name = "Capability Service"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/capability.service"
kind = "service"
requires = [
    "fs.read.all",
    "fs.write.all",
    "process.spawn",
    "service.register",
    "capabilities.manage",
    "device.input",
    "display.read",
    "input.keyboard",
    "input.pointer",
    "ipc.client",
    "ipc.server",
    "usb.access",
]

[prompt]
interactive_capabilities = [
    "window.overlay",
    "input.pointer",
    "input.keyboard",
]
