[package]
name = "update"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("mochios"))'] }

[dependencies]
mochios-certificate-database = { git = "https://github.com/mochiOS/syscalls", package = "mochios-certificate-database", features = ["alloc"] }
mochios-developer-ca-trust = { git = "https://github.com/mochiOS/DeveloperCA", rev = "71f9487a3abe29046e827784502516c9a296c509", package = "mochios-developer-ca-trust" }
mochios-http-client = { git = "https://github.com/mochiOS/syscalls", package = "mochios-http-client" }
mochios-net-device-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-net-device-protocol" }
serde_json = "1"

[target.'cfg(target_os = "mochios")'.dependencies]
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform", default-features = false, features = ["std"] }

[[bin]]
name = "update"
path = "src/main.rs"
test = false
bench = false
harness = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
base64 = "0.22"
ed25519-dalek = "2"
serde = "1"
