[package]
name = "update"
version = "0.1.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("mochios"))'] }

[dependencies]
mochios-http-client = { git = "https://github.com/mochiOS/syscalls", package = "mochios-http-client" }
mochios-net-device-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-net-device-protocol" }

[target.'cfg(target_os = "mochios")'.dependencies]
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform", default-features = false, features = ["std"] }

[[bin]]
name = "update"
path = "src/main.rs"
test = false
bench = false
harness = false

[lib]
path = "src/lib.rs"
