[package]
id = "org.mochios.update"
name = "Update Service"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/update.service"
kind = "service"
requires = [
    "fs.read.all",
    "fs.write.all",
    "ipc.client",
    "ipc.server",
    "net.http.request",
    "signature.db.write",
    "system.time.read",
]
