[service]
id = "org.mochios.service-manager"
name = "Service Manager"
version = "1"
entry = "service-manager.service"

[capabilities]
requires = [
    "fs.read.all",
    "process.spawn",
    "service.register",
    "capabilities.manage",
    "ipc.client",
    "ipc.server",
]
