[package]
name = "service-manager"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform" }
mochi-user-runtime = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-runtime" }
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
mochios-driver-control-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-driver-control-protocol" }

[[bin]]
name = "service-manager"
path = "src/main.rs"
test = false
bench = false
harness = false
