[package]
id = "org.mochios.service-manager"
name = "Service Manager"
version = "1"
vendor = "mochiOS"

[[binary]]
path = "/system/services/service-manager.service"
kind = "service"
requires = [
    "fs.read.all",
    "process.inspect",
    "process.kill",
    "process.spawn",
    "service.register",
    "capabilities.manage",
    "ipc.client",
    "ipc.server",
    "net.connect",
]
