[package]
name = "user-service"
version = "0.1.0"
edition = "2024"

[dependencies]
hmac = { version = "0.12", default-features = false }
mochios-user-database = { git = "https://github.com/mochiOS/syscalls", package = "mochios-user-database", features = ["std"] }
mochios-user-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-user-protocol" }
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform", default-features = false, features = ["std"] }
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
sha2 = { version = "0.10", default-features = false }
zeroize = { version = "1.8", default-features = false }

[lib]
path = "src/lib.rs"

[[bin]]
name = "user-service"
path = "src/main.rs"
test = false
bench = false
harness = false
