[package]
name = "signature"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ed25519-dalek = { version = "2", default-features = false, features = ["alloc"] }
mochios-certificate = { git = "https://github.com/mochiOS/syscalls", package = "mochios-certificate", default-features = false, features = ["alloc"] }
mochios-signature-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-signature-protocol" }
mochi-user-platform = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-platform" }
mochi-user-runtime = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-runtime" }
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
sha2 = { version = "0.10", default-features = false }

[build-dependencies]

[[bin]]
name = "signature"
path = "src/main.rs"
test = false
bench = false
harness = false
